### ISSUE TITLE
When reporting coverage a complete, and error is shown

### ISSUE THREAD

**Issue by jewilmeer** [qltysh/qlty-action#104]
The following github-action returns an error, and the code coverage is not reported;

```yaml
  coverage-complete:
    name: Mark Coverage Complete
    runs-on: ubuntu-latest
    needs:
      - rspec
    steps:
      - name: Mark coverage collection complete
        uses: qltysh/qlty-action/coverage@v1.1.0
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          command: complete
```

It returns the following error:

```
   ERROR   

 > Error opening git repository for retrieving commit metadata
 > 
 > Caused by:
 >     could not find repository at '.'; class=Repository (6); code=NotFound (-3)
```

This is part of a parallel test build, where we report each part separately with: 

```
      - name: Upload coverage to Qlty
        uses: qltysh/qlty-action/coverage@v1.1.0
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/.resultset.json
          total-parts-count: ${{ matrix.ci_node_total }}
```

It was possible to submit the coverage to our main branch, but pull requests do not work :-(
