### ISSUE TITLE
Option to disable Sentry tracking in qlty-action

### ISSUE THREAD

**Issue by labac-p** [qltysh/qlty-action#108]
I’ve noticed that qlty-action integrates with Sentry to track runtime behavior. While this is useful for error reporting and debugging, in some cases users may prefer not to send telemetry data due to privacy, security, or compliance concerns.

**Feature request:**
Please consider adding a configurable option (e.g., an input or environment variable) that allows users to disable Sentry tracking when running the action.

**Example idea:**

```yml
- uses: qltysh/qlty-action@v1
  with:
    disable-sentry: true
```

or:
```yml
env:
  QLTY_DISABLE_SENTRY: true
```
